// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjnJVgSh6VgQHyxWcNZySd5KGvQlLCjvY',
    appId: '1:1040241070357:web:431ff2202c9e2aa0b6d91c',
    messagingSenderId: '1040241070357',
    projectId: 'absensy-jdi0001',
    authDomain: 'absensy-jdi0001.firebaseapp.com',
    databaseURL: 'https://absensy-jdi0001-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'absensy-jdi0001.firebasestorage.app',
    measurementId: 'G-7VNH5VN7CF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_e03THDf-BJfk9qmh2iRFuND2x_4IcqE',
    appId: '1:337718625016:android:9f481c8c126363dc1d310d',
    messagingSenderId: '337718625016',
    projectId: 'absensy-f456e',
    storageBucket: 'absensy-f456e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjxwpcEH8j4_mhDzoP2KRo-eqbX6alItk',
    appId: '1:1040241070357:ios:e7b1a9c9e47df271b6d91c',
    messagingSenderId: '1040241070357',
    projectId: 'absensy-jdi0001',
    databaseURL: 'https://absensy-jdi0001-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'absensy-jdi0001.firebasestorage.app',
    iosBundleId: 'com.example.absensiKaryawan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjxwpcEH8j4_mhDzoP2KRo-eqbX6alItk',
    appId: '1:1040241070357:ios:e7b1a9c9e47df271b6d91c',
    messagingSenderId: '1040241070357',
    projectId: 'absensy-jdi0001',
    databaseURL: 'https://absensy-jdi0001-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'absensy-jdi0001.firebasestorage.app',
    iosBundleId: 'com.example.absensiKaryawan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjnJVgSh6VgQHyxWcNZySd5KGvQlLCjvY',
    appId: '1:1040241070357:web:670b9dac0f371d17b6d91c',
    messagingSenderId: '1040241070357',
    projectId: 'absensy-jdi0001',
    authDomain: 'absensy-jdi0001.firebaseapp.com',
    databaseURL: 'https://absensy-jdi0001-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'absensy-jdi0001.firebasestorage.app',
    measurementId: 'G-5GQPDEWRQQ',
  );
}
